### ISSUE TITLE
Pluralsight links in PDF's

### ISSUE THREAD

**Issue by kevincrocker** [pivotal-education/pcf-developer-cb-old#1]
What link is the correct one to get the latest version of the articulate application that is compatible with PCF v1.11? I've uploaded the right version of articulate into the PCF Dev area on FilesAnyWhere so I can post it into the Pluralsight discussion forum for now.

We actually have a bigger problem in that we have to make the v1.11 course the official one first (i.e. this course) and then we can update the Pluralsight course which has its own update process.

At the moment, our Pluralsight course has the following link which doesn't seem to work.

https://github.com/pivotal-education/pcf-articulate-code (this shows that our version is out of sync with the field engineering sight - if that matters).

BTW, I added all three of the main contributors to our PCF courses as Assignees - that doesn't mean that you all have to fix this. It is for visibility for right now!

**Comment by paulc4** [comment]
Moved to https://github.com/pivotal-education/pcf-developer-cb/issues/1
