### ISSUE TITLE
Pluralsight - we need to refresh the course that exists on this site

### ISSUE THREAD

**Issue by kevincrocker** [pivotal-education/pcf-developer-cb-old#2]
In the discussion board on Pluralsight people are getting errors when they click on specific links in the PDF files. Those links connect to the old content.enablement site.

We need to fix this!

Here's an example

https://pivotal:keepitsimple@content.enablement.pivotal.io/pivotal-cloud-foundry-developer/pcf-developer-basics/service-broker/index.html

The Pluralsight discussion can be seen here:

https://app.pluralsight.com/library/courses/cloud-foundry-developer-1dot7-pivotal/discussion

**Comment by msecrist** [comment]
True - but this is more complicated than it seems. Pluralsight has pretty high standards for their content and if we do it again, I'd like to do it right and their way. Also, I had initially asked Dan to pursue this but as Dan points out, if he's on his way to the PA team, we lose a certified (or trained) resource for working with Pluralsight

**Comment by kevincrocker** [comment]
Yes, Pluralsight is much more complicated and we should set our sights high!

Yes, we do lose a trained resource for working with Pluralsight. Someone else will need to step up - which probably means me!

**Comment by paulc4** [comment]
Moved to https://github.com/pivotal-education/pcf-developer-cb/issues/2
