### ISSUE TITLE
On-demand services

### ISSUE THREAD

**Issue by dbuchko** [pivotal-education/pcf-developer-cb-old#4]
Need to update the Service Brokers module for on-demand services.  (Existing MySQL example is out-of-date.)  Could also mention the Open Service Broker OSS project (https://openservicebrokerapi.org/).

**Comment by msecrist** [comment]
Want to make sure to note that if this is a Pivotal value-add we make sure to capture for inclusion in the cf dev material with value adds.

**Comment by paulc4** [comment]
Moved to https://github.com/pivotal-education/pcf-developer-cb/issues/4
