### ISSUE TITLE
Blue-green lab uses shell script which doesn't work on Windows

### ISSUE THREAD

**Issue by dbuchko** [pivotal-education/pcf-developer-cb-old#5]
At the end of the blue-green lab, when using the blue-green plugin it attempts to invoke the test-health.sh script.  This doesn't work on Windows.

**Comment by kevincrocker** [comment]
ah, we need an equivalent Windows .bat file

**Comment by paulc4** [comment]
Moved to https://github.com/pivotal-education/pcf-developer-cb/issues/5
